version: '3.9'
services:
  user_management_db:
    image: postgres:latest
    container_name: user_management_db
    volumes:
      - ./data:/data
    ports:
      - '5533:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=user_management_db'